### ISSUE TITLE
Maintain log of harvesting times

### ISSUE THREAD

**Issue by larilampen** [TheLanguageArchive/oai-harvest-manager#1]
A log of previous harvests (per provider) and their timestamps should be maintained, e.g. in a file. This is needed for two purposes: to obtain the timestamp needed when using incremental harvesting to get updated records since the last harvest, and for information, e.g. to show to providers who wish to know when / how often they have been harvested. For the latter purpose the log could perhaps include some statistics e.g. number of harvested records and number of records with errors.

**Comment by kjvandelooij** [comment]
The next release of the harvest manager resolves this issue.
