### ISSUE TITLE
Harvesting when multiple OAI-PMH servers at the same centre

### ISSUE THREAD

**Issue by ttrippel** [TheLanguageArchive/oai-harvest-manager#2]
When a centre has more than one OAI-PMH server providing metadata, currently only the first address is being harvested. For example if a centre runs more than one repository, each with a separate OAI-PMH server, only the first one is used, the second one is ignored. But the centre registry allows to have that. The XPATH interpreting the centre registry does not implement that, which is a bug.

**Comment by kjvandelooij** [comment]
This next release of the harvest manager resolves this issue.
